swagger: '2.0'

info:
  version: "1.0.0"
  title: PDF Generation API

paths:
  /v1.0/llc1:
    post:
      description: |
        Generate an LLC1 PDF and return the URL to the document.
      parameters:
        -
          in: body
          name: Extents
          required:
            - 'extents'
          schema:
            type: object
            properties:
              description:
                type: string
              extents:
                $ref: '#/definitions/FeatureCollection'
      produces:
        - application/json
      responses:
        201:
          description: Successful response
          examples:
            json: {
                      "document_url": "http://storage-api/llc1/b929d908-90f9-413e-a851-8678f9de77f5"
                  }

        400:
          description: Bad request

        500:
          description: Application error

security:
  - JWTAuth: []
  
securityDefinitions:
  JWTAuth:
    type: apiKey
    in: header
    name: Authorizaton

definitions:
  FeatureCollection:
    type: object
    description: A collection of Feature objects wrapping a GeoJSon geometry
    required:
      - 'type'
      - 'features'
    properties:
      type:
        type: string
        enum:
          - 'FeatureCollection'
      features:
        type: array
        items:
          $ref: '#/definitions/Feature'

  Feature:
    type: object
    description: A single Feature object wrapping a GeoJSon geometry
    required:
      - 'type'
      - 'geometry'
      - 'properties'
    properties:
      type:
        type: string
        enum:
          - 'Feature'
      geometry:
        type: object
        $ref: '#/definitions/Geometry'
      properties:
        type: object
        description: Should either be an object or null.

  Geometry:
    type: object
    description: Geometry defining a GeoJSon extent
    discriminator: type
    required:
      - type
    properties:
      coordinates:
        type: object
        description: Should match the definition of; Polygon or MultiPolygon's coordinates.
      type:
        type: string
        enum:
        - 'Polygon'
        - 'MultiPolygon'
        description: The geometry type.

  Point2D:
    type: array
    description: GeoJSon 2D Point
    minItems: 2
    maxItems: 2
    items:
      type: number

  Polygon:
    type: object
    description: Polygon GeoJSon geometry
    properties:
      coordinates:
        type: array
        items:
          type: array
          items:
            $ref: '#/definitions/Point2D'

  MultiPolygon:
    type: object
    description: Multi Polygon GeoJSon geometry
    properties:
      coordinates:
        type: array
        items:
          type: array
          items:
            type: array
            items:
              $ref: '#/definitions/Point2D'
